foods/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('recipes/', include('recipes.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.IndexView.as_view(),name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/',views.RecipeCreateView.as_view(),name='recipe_new')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('signup/', views.create_user, name='create_user'),
    path('login/',views.login, name='login'),
]

recipes/models.py
from django.db import models
from users.models import CustomUser
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.




class Recipe(models.Model):
    name = models.CharField(max_length=32)
    cuisine = models.CharField(max_length=16)
    difficulty = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    pub_date = models.DateField('date published')
    publisher = CustomUser()
    comments = ArrayField(
        ArrayField(
                models.CharField(max_length=255,blank=True),
        )
    )
    image = models.ImageField(upload_to='gallery')
    rating = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    price = models.IntegerField()
    instructions = models.CharField(max_length=2048)
    video = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Gallery(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    img = models.ImageField()


class ingredient(models.Model):
    recipe = models.ForeignKey(Recipe,on_delete=models.CASCADE)

    name = models.CharField(max_length=16)
    img = models.ImageField(blank=True)
    origin = models.CharField(max_length=16,blank=True)
    information = models.CharField(max_length=255,blank=True)
    amount = models.CharField(max_length=16)

    def __str__(self):
        return self.name


class equipment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    name = models.CharField(max_length=32)
    price_range = models.CharField(max_length=16)
    desc = models.CharField(max_length=255)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    username = models.CharField(max_length=16)
    password = models.CharField(max_length=32)
    name = models.CharField(max_length=16,default='')
    last_name = models.CharField(max_length=16,default='')
    info = models.CharField(max_length=255,default='')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CreateUser(forms.Form):
    username = forms.CharField(label='Username',max_length=16)
    email = forms.EmailField(label='Email')
    password_1 = forms.CharField(label='Password',max_length=16,widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password',max_length=16, widget=forms.PasswordInput)
    name = forms.CharField(label='Name',max_length=16)
    last_name = forms.CharField(label='Last Name', max_length=16)
    information = forms.CharField(label='Description',required=False)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class LoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Password',max_length=16,widget=forms.PasswordInput)

recipes/views.py
from django.shortcuts import render
from django.views import generic
from .models import Recipe,ingredient,equipment
from django.views.generic import CreateView
# Create your views here.
class IndexView(generic.ListView):
    template_name = 'recipes/index.html'
    context_object_name = 'latest_recipe_list'

    def get_queryset(self):
        return Recipe.objects.all()

class DetailView(generic.DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'

class RecipeCreateView(CreateView):
    model = Recipe
    fields = ('name','cuisine','difficulty','pub_date','image','rating','price','instructions','video')
    success_url = "/recipes"

users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import render
from .models import CustomUser
from .forms import CreateUser, LoginForm
from django import forms

def create_user(request):

    if request.method == 'POST':
        form = CreateUser(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password_1 = form.cleaned_data['password_1']
            password_2 = form.cleaned_data['password_2']
            if password_1 and password_2 and password_1 != password_2:
                raise forms.ValidationError("Passwords don't match")
            name = form.cleaned_data['name']
            last_name = form.cleaned_data['last_name']
            information = form.cleaned_data['information']
            new_user = CustomUser(email=email,
                       username=username,
                       password=password_1,
                       name=name,
                       last_name=last_name,
                       info=information)
            new_user.save()
            return HttpResponseRedirect('/users/login')
    else:
            form = CreateUser()
    return render(request, 'createUser.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            try:
                valid = CustomUser.objects.filter(email=email)
            except:
                raise forms.ValidationError("Incorrect Email or Password")
            valid_password = valid.password
            if password == valid_password:
                return HttpResponseRedirect('/')

        else:
            form = LoginForm()

        return render(request,'login.html',{'form':form})

recipes/templates/recipes/detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>{{ recipe.name }}</h1>
    <div class="row">
        <div class="col" style="background-color:red;">{{recipe.cuisine}}</div>
    </div>
    <img src="{{recipe.image.url}}" class="img" alt="Carbonara" width="304" height="236">
    <div class="container-fluid">
        <h3>Difficulty</h3>
        <h4>{{ recipe.difficulty }}/10</h4>
    </div>
    <h2>Ingredients</h2>
    <ul class="list-group">
        {% for ingredient in recipe.ingredient_set.all %}
            <li class="list-group-item">{{ingredient.name}}--{{ingredient.amount}}</li>
        {%endfor%}
    </ul>
    <iframe width="800" height="600"
            src="{{recipe.video}}" frameborder="0" allowfullscreen></iframe>
    <h2>Instructions</h2>
    <p class="lead">{{recipe.instructions}}</p>
</div>
{% endblock %}

recipes/templates/recipes/index.html
{% extends "base.html" %}

{% block content %}
{% if latest_recipe_list %}
<div class="container-fluid">
        <ul class="list-group">
        {% for recipe in latest_recipe_list %}
            <li class="list-group-item"><a href="{% url 'recipes:detail' recipe.id %}">{{ recipe.name }}</a></li>
            <img src="{{recipe.image.url}}" class="img" alt="Carbonara" width="304" height="236">
        {% endfor %}
        </ul>
    {% else %}
        <p>No recipes are available.</p>
    {% endif %}
</div>
{% endblock %}

recipes/templates/recipes/recipe_form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

</head>
<body>
<div class="row" style="background-image:url(media/bg_1.jpg)">
  <img src="media/bg_1.jpg">
</div>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="/">Foods</a>

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="admin">Admin</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="users/signup">SignUp</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="users/login">Login</a>
    </li>
  </ul>
</nav>
  <main>

    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container" style="margin-top:30px">
      <h3>Actions</h3>
      <div class="nav nav-pills flex-column">
        <li class="nav-item">
          <a class="nav-link active" href="recipes/">View Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="recipes/create">Create Your Recipe</a>
        </li>
      </div>
</div>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}

users/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

users/templates/createUser.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock %}
{% block content %}
<form action="/users/signup/" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

users/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a> |
  <a href="{% url 'signup' %}">signup</a>
{% endif %}
{% endblock %}

users/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="form-group">
      <label for="usr">Name:</label>
      <input type="text" class="form-control" id="usr" name="username">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

users/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}